# Generated by Django 5.0.14 on 2025-09-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleModelWithAlternativeInterface",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
