# Generated by Django 4.1.9 on 2023-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorpage",
            name="nickname",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
