# Generated by Django 3.2.15 on 2022-08-11 10:15

from django.db import migrations

from wagtail.fields import RichTextField


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_blogpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="summary",
            field=RichTextField(blank=True),
        ),
    ]
