# Generated by Django 3.2.15 on 2022-09-09 09:59

from django.db import migrations

try:
    from wagtail.fields import RichTextField
except ImportError:
    # Wagtail < 3.0
    from wagtail.core.fields import RichTextField


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_blogpage_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="extra_rich_text",
            field=RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="advert",
            name="rich_text",
            field=RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="extra_summary",
            field=RichTextField(blank=True),
        ),
    ]
