# Generated by Django 3.2.16 on 2022-12-02 05:10

from django.db import migrations, models
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220909_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddlewareModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
