# Generated by Django 2.2.1 on 2019-06-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("home", "0006_socialmediasettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        )
    ]
