# Generated by Django 2.2.10 on 2020-02-27 11:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0013_auto_20191030_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.CharField(max_length=255)),
                ('thank_you_text', wagtail.core.fields.RichTextField()),
                ('cover_image', models.ForeignKey(help_text="Recommended image size 1400x787-2000x1125px (16:9), smaller images won't have as much of an impact and portrait images will be manipulated.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('cover_logo', models.ForeignKey(blank=True, help_text="If empty, this will be your organisation's logo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('thank_you_image', models.ForeignKey(blank=True, help_text="Recommended image size 1400x787-2000x1125px (16:9), smaller images won't have as much of an impact and portrait images will be manipulated.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
    ]
