# Generated by Django 2.2.10 on 2020-03-03 12:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [("home", "0013_auto_20191030_1159")]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    ("heading", wagtail.core.blocks.CharBlock(classname="full title")),
                    ("paragraph", wagtail.core.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("decimal", wagtail.core.blocks.DecimalBlock()),
                    ("date", wagtail.core.blocks.DateBlock()),
                    ("datetime", wagtail.core.blocks.DateTimeBlock()),
                    (
                        "gallery",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(
                                        classname="full title"
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "caption",
                                                            wagtail.core.blocks.CharBlock(
                                                                classname="full title"
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "youtube_link",
                                    wagtail.embeds.blocks.EmbedBlock(required=False),
                                )
                            ]
                        ),
                    ),
                    (
                        "objectives",
                        wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()),
                    ),
                ]
            ),
        )
    ]
