# Generated by Django 2.2.13 on 2020-06-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('home', '0014_auto_20200303_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
