# Generated by Django 2.2.14 on 2020-08-03 22:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [("home", "0014_auto_20200303_1234")]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    ("heading", wagtail.core.blocks.CharBlock(classname="full title")),
                    ("paragraph", wagtail.core.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("decimal", wagtail.core.blocks.DecimalBlock()),
                    ("date", wagtail.core.blocks.DateBlock()),
                    ("datetime", wagtail.core.blocks.DateTimeBlock()),
                    (
                        "gallery",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(
                                        classname="full title"
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "caption",
                                                            wagtail.core.blocks.CharBlock(
                                                                classname="full title"
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "youtube_link",
                                    wagtail.embeds.blocks.EmbedBlock(required=False),
                                )
                            ]
                        ),
                    ),
                    (
                        "objectives",
                        wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()),
                    ),
                    (
                        "carousel",
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    "text",
                                    wagtail.core.blocks.CharBlock(
                                        classname="full title"
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ]
                        ),
                    ),
                    (
                        "text_and_buttons",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("text", wagtail.core.blocks.TextBlock()),
                                (
                                    "buttons",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "button_text",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Text",
                                                        max_length=50,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "button_link",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Link",
                                                        max_length=255,
                                                        required=True,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ]
            ),
        )
    ]
