# Generated by Django 3.1.3 on 2020-11-24 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("home", "0018_add_pagechooserblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
