# Generated by Django 2.2.10 on 2020-03-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_simplemodel"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="cover",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
    ]
