# Generated by Django 3.2.14 on 2022-07-25 13:13

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.core.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("paragraph", wagtail.core.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("decimal", wagtail.core.blocks.DecimalBlock()),
                    ("date", wagtail.core.blocks.DateBlock()),
                    ("datetime", wagtail.core.blocks.DateTimeBlock()),
                    (
                        "gallery",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(
                                        form_classname="full title"
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "caption",
                                                            wagtail.core.blocks.CharBlock(
                                                                form_classname="full title"
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "youtube_link",
                                    wagtail.embeds.blocks.EmbedBlock(required=False),
                                )
                            ]
                        ),
                    ),
                    (
                        "objectives",
                        wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()),
                    ),
                    (
                        "carousel",
                        wagtail.core.blocks.StreamBlock(
                            [
                                (
                                    "text",
                                    wagtail.core.blocks.CharBlock(
                                        form_classname="full title"
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("markup", wagtail.core.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "callout",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("text", wagtail.core.blocks.RichTextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ]
                        ),
                    ),
                    (
                        "text_and_buttons",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("text", wagtail.core.blocks.TextBlock()),
                                (
                                    "buttons",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "button_text",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Text",
                                                        max_length=50,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "button_link",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Link",
                                                        max_length=255,
                                                        required=True,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "mainbutton",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "button_text",
                                                wagtail.core.blocks.CharBlock(
                                                    label="Text",
                                                    max_length=50,
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "button_link",
                                                wagtail.core.blocks.CharBlock(
                                                    label="Link",
                                                    max_length=255,
                                                    required=True,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("page", wagtail.core.blocks.PageChooserBlock()),
                    (
                        "text_with_callable",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("text", wagtail.core.blocks.CharBlock()),
                                ("integer", wagtail.core.blocks.IntegerBlock()),
                                ("decimal", wagtail.core.blocks.FloatBlock()),
                            ]
                        ),
                    ),
                    (
                        "block_with_name",
                        wagtail.core.blocks.StructBlock(
                            [("name", wagtail.core.blocks.TextBlock())]
                        ),
                    ),
                ],
            ),
        ),
    ]
