# Generated by Django 3.2.14 on 2022-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_blogpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSocialMediaSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField(help_text="Your Facebook page URL")),
                (
                    "instagram",
                    models.CharField(
                        help_text="Your Instagram username, without the @",
                        max_length=255,
                    ),
                ),
                (
                    "trip_advisor",
                    models.URLField(help_text="Your Trip Advisor page URL"),
                ),
                (
                    "youtube",
                    models.URLField(
                        help_text="Your YouTube channel or user account URL"
                    ),
                ),
            ],
        ),
    ]
