# Generated by Django 3.2.15 on 2022-08-11 10:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_globalsocialmediasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='summary',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
